import { build } from "esbuild";
import fs from "node:fs/promises";

// Ship the actual Lucide icons as a browser-native module. The published root
// must work without npm, a bundler, an import map, or a third-party CDN.
const source = await fs.readFile("modules/icons.js", "utf8");
const names = source.match(
  /import\s*\{([^}]+)\}\s*from\s*"\.\.\/vendor\/lucide\.js"/,
)?.[1];
if (!names) throw new Error("Lucide import not found in modules/icons.js");
const { version } = JSON.parse(
  await fs.readFile("node_modules/lucide/package.json", "utf8"),
);
await fs.mkdir("vendor", { recursive: true });
await build({
  stdin: {
    contents: `export {${names}} from "lucide";`,
    resolveDir: process.cwd(),
    sourcefile: "lucide-entry.js",
  },
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  outfile: "vendor/lucide.js",
  banner: {
    js: `// Generated by npm run vendor:icons. Lucide ${version}; see lucide.LICENSE.`,
  },
});
await fs.copyFile("node_modules/lucide/LICENSE", "vendor/lucide.LICENSE");
